In [3]:
import torch

x = torch.empty(5)
print("empty(1) : ",x)
print()

x = torch.empty(2,3)
print("empty(2,3)",x)
print()

x = torch.empty(2,2,3)
print("empty(2,2,3)",x)
print()

x = torch.rand(5,3)
print("torch rand(5,3) : ",x)
print()

x = torch.zeros(5,3)
print("torch zeros(5,3) : ",x)
print()



empty(1) :  tensor([0., 0., 0., 0., 0.])

empty(2,3) tensor([[0., 0., 0.],
        [0., 0., 0.]])

empty(2,2,3) tensor([[[8.6699e-22, 2.0963e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])

torch rand(5,3) :  tensor([[0.1938, 0.2477, 0.0695],
        [0.8185, 0.9175, 0.3197],
        [0.1956, 0.6754, 0.9968],
        [0.5473, 0.3336, 0.3468],
        [0.3303, 0.4387, 0.9463]])

torch zeros(5,3) :  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])



In [5]:
print(x.shape)
print(x.shape[0],x.shape[1])

torch.Size([5, 3])
5 3


In [6]:
x = torch.tensor([4.5,1,3,5])
print(x)
print(x.dtype)

tensor([4.5000, 1.0000, 3.0000, 5.0000])
torch.float32


In [7]:
x = torch.tensor([4.5,3],requires_grad=True)
print(x)

tensor([4.5000, 3.0000], requires_grad=True)


In [12]:
x = torch.ones(3,2)
y = torch.rand(3,2)
print(torch.add(x,y))

tensor([[1.8388, 1.4363],
        [1.2664, 1.9304],
        [1.6593, 1.3199]])


In [16]:
x = torch.ones(3,2)
y = torch.rand(2,3)
print(y)
print(torch.matmul(x,y))

tensor([[0.8949, 0.4608, 0.7747],
        [0.9170, 0.4717, 0.6957]])
tensor([[1.8119, 0.9326, 1.4705],
        [1.8119, 0.9326, 1.4705],
        [1.8119, 0.9326, 1.4705]])


In [17]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [18]:
x = torch.rand(10,10,device=device)
print(x)

tensor([[0.0062, 0.6650, 0.8088, 0.1825, 0.0497, 0.8183, 0.7953, 0.5916, 0.6533,
         0.1093],
        [0.4089, 0.8551, 0.0242, 0.8195, 0.0752, 0.2572, 0.0583, 0.1369, 0.8128,
         0.1411],
        [0.7913, 0.7704, 0.8513, 0.2365, 0.9464, 0.3255, 0.4079, 0.3316, 0.1948,
         0.8558],
        [0.7497, 0.2354, 0.8459, 0.9567, 0.8703, 0.0608, 0.7966, 0.0688, 0.5712,
         0.0195],
        [0.4808, 0.4690, 0.5356, 0.9809, 0.5221, 0.5331, 0.9474, 0.9238, 0.7290,
         0.7773],
        [0.2060, 0.3447, 0.8929, 0.9192, 0.8168, 0.1305, 0.9160, 0.4788, 0.8838,
         0.8304],
        [0.7694, 0.5341, 0.7339, 0.1206, 0.3784, 0.2705, 0.1298, 0.0150, 0.0828,
         0.8834],
        [0.9410, 0.4650, 0.5860, 0.2860, 0.6720, 0.5975, 0.4636, 0.7977, 0.8763,
         0.4206],
        [0.2397, 0.4355, 0.9807, 0.4824, 0.1965, 0.6245, 0.2618, 0.5643, 0.8333,
         0.4056],
        [0.7910, 0.2736, 0.5202, 0.7087, 0.2597, 0.0498, 0.0514, 0.7481, 0.7883,
         0.6721]], device='c

In [24]:
import torch
import time

# Check if CUDA is available
if not torch.cuda.is_available():
    print("CUDA is not available. Please make sure your PyTorch installation has CUDA support.")
else:
    print("CUDA is available!")

# Define a function to benchmark matrix multiplication on CPU and GPU
def benchmark_matrix_multiplication(size):
    # Create random matrices
    A = torch.randn(size, size)
    B = torch.randn(size, size)

    # Perform matrix multiplication on CPU
    start_time = time.time()
    C_cpu = torch.matmul(A, B)
    cpu_time = time.time() - start_time

    # Move matrices to GPU
    A_gpu = A.to('cuda')
    B_gpu = B.to('cuda')

    # Perform matrix multiplication on GPU
    torch.cuda.synchronize()  # Ensure all GPU operations are complete
    start_time = time.time()
    C_gpu = torch.matmul(A_gpu, B_gpu)
    torch.cuda.synchronize()  # Ensure all GPU operations are complete
    gpu_time = time.time() - start_time

    return cpu_time, gpu_time

# Set matrix size for benchmarking
matrix_size = 10  # You can adjust this size to your needs

# Run the benchmark
cpu_time, gpu_time = benchmark_matrix_multiplication(matrix_size)

# Print the results
print(f"Matrix size: {matrix_size}x{matrix_size}")
print(f"CPU time: {cpu_time:.6f} seconds")
print(f"GPU time: {gpu_time:.6f} seconds")
print(f"Speedup: {cpu_time / gpu_time:.2f}x")


CUDA is available!
Matrix size: 10x10
CPU time: 0.002996 seconds
GPU time: 0.025887 seconds
Speedup: 0.12x


In [28]:
## Gradient
# Define a tensor with gradient tracking enabled
x = torch.tensor(10.0, requires_grad=True)
print(x)
print()

# perform operations on the tensor y=x^2
y = x**2
print(y)
print()

# calculate the gradient of y with respect to x [ dy/dx = d(x^2)/dx = 2x ] 
y.backward()
print(x.grad)
print()

tensor(10., requires_grad=True)

tensor(100., grad_fn=<PowBackward0>)

tensor(20.)



In [39]:
# Linear regression Autograd
x = torch.tensor([1,2,3,4,5,6,7])
y = torch.tensor([2,4,6,8,10,12,14])
weight = torch.tensor(4.0,requires_grad=True)

def forward(x):
    return x*weight

def loss_function(y_pred,y):
    return ((y_pred - y)**2).mean()

x_test = 6
forward(6)


tensor(24., grad_fn=<MulBackward0>)

In [42]:
# Linear regression Autograd
x = torch.tensor([1,2,3,4,5,6,7],dtype=torch.float32)
y = torch.tensor([2,4,6,8,10,12,14],dtype=torch.float32)
weight = torch.tensor(4.0,requires_grad=True)

def forward(x):
    return x*weight

def loss_function(y_pred,y):
    return ((y_pred - y)**2).mean()

x_test = 6
forward(torch.tensor(6))

lr = 0.01
for epoch in range(50):
    
    y_pred = forward(x)
    loss = loss_function(y_pred,y)
    loss.backward()
    with torch.no_grad():
        weight.data = weight.data - lr * weight.grad
    weight.grad.zero_()
    print(f"weight : {weight.item()}, loss : {loss.item()}")

weight : 3.1999998092651367, loss : 80.0
weight : 2.7199997901916504, loss : 28.79998779296875
weight : 2.431999921798706, loss : 10.367995262145996
weight : 2.259199857711792, loss : 3.7324790954589844
weight : 2.155519962310791, loss : 1.3436909914016724
weight : 2.0933120250701904, loss : 0.48372918367385864
weight : 2.0559871196746826, loss : 0.17414256930351257
weight : 2.0335922241210938, loss : 0.0626910850405693
weight : 2.020155429840088, loss : 0.022568749263882637
weight : 2.0120933055877686, loss : 0.008124832063913345
weight : 2.007256031036377, loss : 0.0029249468352645636
weight : 2.0043535232543945, loss : 0.0010530018480494618
weight : 2.0026121139526367, loss : 0.0003790633345488459
weight : 2.0015673637390137, loss : 0.00013646279694512486
weight : 2.0009403228759766, loss : 4.913215525448322e-05
weight : 2.0005640983581543, loss : 1.7684142221696675e-05
weight : 2.000338554382324, loss : 6.363985448842868e-06
weight : 2.0002031326293945, loss : 2.2923813958186656e-0

In [43]:
forward(10)

tensor(20.0000, grad_fn=<MulBackward0>)

In [45]:
x = torch.tensor([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]],dtype=torch.float32)
y = torch.tensor([[2],[4],[6],[8],[10],[12],[14],[16],[18],[20]],dtype=torch.float32)

n_samples,n_features = x.shape
print(n_samples,n_features)

x_test = torch.tensor([45],dtype=torch.float32)

10 1


In [46]:
class LinearRegression(torch.nn.Module):
    def __init__(self,input_dim,output_dim):
        super(LinearRegression,self).__init__()
        self.linear = torch.nn.Linear(input_dim,output_dim)
        
    def forward(self,x):
        return self.linear(x)

In [47]:
input_shape ,output_shape = n_features,n_features
model = LinearRegression(n_features,n_features)

In [49]:
# prediction before the training
model(x_test)

tensor([37.1818], grad_fn=<ViewBackward0>)

In [53]:
ler = 0.01
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(),lr=ler)
for epoch in range(300):
    model.train()
    y_pred = model(x)
    loss = criterion(y_pred,y)
    
    loss.backward() 
    
    #update weights
    optimizer.step()
    
    #zero the grad after updating
    optimizer.zero_grad()
    
    if (epoch+1)%10 == 0:
        print(f"epoch : {epoch+1}, loss : {loss.item():.4f}")
    
    # prediction after the training
model(x_test)

epoch : 10, loss : 0.0822
epoch : 20, loss : 0.0585
epoch : 30, loss : 0.0398
epoch : 40, loss : 0.0259
epoch : 50, loss : 0.0160
epoch : 60, loss : 0.0093
epoch : 70, loss : 0.0051
epoch : 80, loss : 0.0027
epoch : 90, loss : 0.0013
epoch : 100, loss : 0.0006
epoch : 110, loss : 0.0002
epoch : 120, loss : 0.0001
epoch : 130, loss : 0.0000
epoch : 140, loss : 0.0000
epoch : 150, loss : 0.0000
epoch : 160, loss : 0.0000
epoch : 170, loss : 0.0000
epoch : 180, loss : 0.0000
epoch : 190, loss : 0.0000
epoch : 200, loss : 0.0000
epoch : 210, loss : 0.0000
epoch : 220, loss : 0.0000
epoch : 230, loss : 0.0000
epoch : 240, loss : 0.0000
epoch : 250, loss : 0.0000
epoch : 260, loss : 0.0000
epoch : 270, loss : 0.0000
epoch : 280, loss : 0.0000
epoch : 290, loss : 0.0000
epoch : 300, loss : 0.0000


tensor([90.], grad_fn=<ViewBackward0>)